quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

quarkus.http.port=${QUARKUS_HTTP_PORT:8085}

# Valid Transactions In
mp.messaging.incoming.valid-transactions-in.connector=smallrye-kafka
mp.messaging.incoming.valid-transactions-in.topic=valid-transactions
mp.messaging.incoming.valid-transactions-in.group.id=notification-group

# Fraud Alerts In
mp.messaging.incoming.fraud-alerts-in.connector=smallrye-kafka
mp.messaging.incoming.fraud-alerts-in.topic=fraud-alerts
mp.messaging.incoming.fraud-alerts-in.group.id=notification-group

