quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

quarkus.http.port=${QUARKUS_HTTP_PORT:8081}

# Raw Transactions Out
mp.messaging.outgoing.raw-transactions-out.connector=smallrye-kafka
mp.messaging.outgoing.raw-transactions-out.topic=raw-transactions

