quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

quarkus.http.port=${QUARKUS_HTTP_PORT:8083}

# Raw Transactions In
mp.messaging.incoming.raw-transactions-in.connector=smallrye-kafka
mp.messaging.incoming.raw-transactions-in.topic=raw-transactions
mp.messaging.incoming.raw-transactions-in.group.id=fraud-check-group

# Fraud Alerts Out
mp.messaging.outgoing.fraud-alerts-out.connector=smallrye-kafka
mp.messaging.outgoing.fraud-alerts-out.topic=fraud-alerts

# Valid Transactions Out
mp.messaging.outgoing.valid-transactions-out.connector=smallrye-kafka
mp.messaging.outgoing.valid-transactions-out.topic=valid-transactions
